### ISSUE TITLE
the right way to start okc-ssh-agent

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/okc-agents#2]
I have
```
ssh_socket=$HOME/../usr/tmp/okc
okc-ssh-agent $ssh_socket 2>/dev/null &|
export SSH_AUTH_SOCK=$ssh_socket
```
at the end of my zshrc.

I don't see into why, but sometimes I need to `rm $SSH_AUTH_SOCK` and restart termux.

**Comment by 532910** [comment]
Looks like it should be:
```
export SSH_AUTH_SOCK=$HOME/.ssh/.S_okc-agent
pidof okc-ssh-agent > /dev/null || {
        rm -f $SSH_AUTH_SOCK
        okc-ssh-agent $SSH_AUTH_SOCK &|
}
```

**Comment by 532910** [comment]
Readme should be updated.

**Comment by DDoSolitary** [comment]
It is expected that okc-ssh-agent will fail if the socket file already exists even if there's no process listening on it. It is consistent with the POSIX `bind` function and the behavior of `ssh-agent`. However, some other current limitations does make this behavior pretty annoying:

- ssh-agent will automatically generate a unique file name if no name is given (`$TMPDIR/ssh-XXXXXXXXXX/agent.<ppid>`), but okc-ssh-agent currently requires a manually specified name.
- okc-ssh-agent only deletes the socket file on exit triggered by Ctrl+C (`SIGINT`), but ssh-agent does the deletion on some other exit signals as well (e.g. `SIGTERM` and `SIGHUP`)

I plan to implement these missing features so that file name conflict will not happen normally.

**Comment by 532910** [comment]
> to implement these missing features

Not sure if this is required, though possible the same behavior will be more obvious. Anyway something should start it. For example on my desktop it's done with scripts in `/etc/X11/Xsession.d`, and 90gpg-agent uses always the same socket for ssh agent emulation: `/run/user/1000/gnupg/S.gpg-agent.ssh`

**Comment by DDoSolitary** [comment]
> Anyway something should start it.

IMO, it's the user's job to write the startup script. Though I do agree that it is a good idea to put an example script in readme.

**Comment by 532910** [comment]
Yep, exactly, I opened this issue to help users write their scripts!

**Comment by DDoSolitary** [comment]
Done.
